name:                testBot1
version:             0.1.0.0
github:              "githubuser/testBot1"
license:             BSD3
author:              "ottoMuller"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/testBot1#readme>

dependencies:
- base >= 4.7 && < 5
- yaml
- http-conduit
- bytestring
- aeson
- datetime

library:
  source-dirs: src

executables:
  testBot1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - testBot1

tests:
  testBot1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - testBot1
